language: node_js
node_js:
  - "6"
script:
  - cd recorder && npm install && npm run build
  - cd remote && npm install && npm test
notifications:
  email: false
cache:
  directories:
    - node_modules
    - recorder/node_modules
