language: node_js
node_js:
  - "6"
env:
  - APP=recorder
  - APP=remote framework=vanilla
  - APP=remote framework=jquery
  - APP=remote framework=angular
  - APP=remote framework=react
script:
  - cd $APP && npm install && npm test
notifications:
  email: false
cache:
  directories:
    - node_modules
    - recorder/node_modules
    - remote/node_modules
