language: node_js
node_js:
  - "6"
env:
  - APP=recorder
  - APPremote
script:
  - cd $APP && npm install && npm test
notifications:
  email: false
cache:
  directories:
    - node_modules
    - recorder/node_modules
